import { IProduct } from './product.model';

export const productsJSON: IProduct[] = [

    {
      id: '1',
      name: 'Kebab med tre pepperoni',
      description: "Картина з зображенням вертела з трьома зеленими чилі.",
      category: 'VANILLA',
      price: 15.99,
      imageUrl: './products/vanilla/Kebab.webp',
      rating: 4.5,
      stock: 10
    },
    {
      id: '2',
      name: 'De_aztec',
      description: "Картина з карткою De_aztec з гри Counter Strike.",
      category: 'VANILLA',
      price: 15.99,
      imageUrl: './products/vanilla/De_aztec.webp',
      rating: 4.7,
      stock: 10
    },
    {
      id: '3',
      name: 'Albanian',
      description: "Чоловік у фезі біля будинку і куща.",
      category: 'VANILLA',
      price: 15.99,
      imageUrl: './products/vanilla/Albanian.webp',
      rating: 4.6,
      stock: 10
    },
    {
      id: '4',
      name: 'De_aztec 2',
      description: "Картина з карткою De_aztec 2 з гри Counter Strike.",
      category: 'VANILLA',
      price: 15.99,
      imageUrl: './products/vanilla/De_aztec 2.webp',
      rating: 4.7,
      stock: 10
    },
    {
      id: '5',
      name: 'Target Successfully Bombed',
      description: "Картина з карти De_dust2 з гри Counter Strike, що має назву «ціль успішно бомбардувана».",
      category: 'VANILLA',
      price: 15.99,
      imageUrl: './products/vanilla/Target Successfully Bombed.webp',
      rating: 4.8,
      stock: 10
    },
    {
      id: '6',
      name: 'Paradisträd',
      description: "Картина з натюрмортом двох рослин у горщиках.",
      category: 'VANILLA',
      price: 15.99,
      imageUrl: './products/vanilla/Paradisträd.webp',
      rating: 4.6,
      stock: 10
    },
    {
      id: '7',
      name: 'Wasteland',
      description: "Пустеля на задньому фоні і кролик, що сидить на підвіконні.",
      category: 'VANILLA',
      price: 15.99,
      imageUrl: './products/vanilla/Wasteland.webp',
      rating: 4.5,
      stock: 10
    },
    {
      id: '8',
      name: 'Meditative',
      description: "Майнкрафтова видалена троянда, створена за мотивами картини Сальвадора Далі «Медитативна троянда».",
      category: 'VANILLA',
      price: 15.99,
      imageUrl: './products/vanilla/Meditative.webp',
      rating: 4.9,
      stock: 10
    },
    {
      id: '9',
      name: 'Wanderer',
      description: "Людина, що стоїть, картина за мотивами знаменитої картини Каспара Давіда Фрідріха «Мандрівник над морем туману».",
      category: 'VANILLA',
      price: 15.99,
      imageUrl: './products/vanilla/Wanderer.webp',
      rating: 4.7,
      stock: 10
    },
    {
      id: '10',
      name: 'Graham',
      description: "Король Грем з гри King's Quest.",
      category: 'VANILLA',
      price: 15.99,
      imageUrl: './products/vanilla/Graham.webp',
      rating: 4.8,
      stock: 10
    },
    {
      id: '11',
      name: 'Prairie Ride',
      description: "Нооор з дефолтним виглядом Minecraft, який їде на коні, за мотивами картини Фредеріка Ремінгтона «Ковбой».",
      category: 'VANILLA',
      price: 15.99,
      imageUrl: './products/vanilla/Prairie Ride.webp',
      rating: 4.6,
      stock: 10
    },
    {
      id: '12',
      name: 'The Pool',
      description: "Люди, що відпочивають і купаються в квадратному басейні.",
      category: 'VANILLA',
      price: 15.99,
      imageUrl: './products/vanilla/The Pool.webp',
      rating: 4.7,
      stock: 10
    },
    {
      id: '13',
      name: 'Bonjour Monsieur Courbet',
      description: "Двоє пішоходів з загостреними бородами вітаються.",
      category: 'VANILLA',
      price: 15.99,
      imageUrl: './products/vanilla/Bonjour Monsieur Courbet.webp',
      rating: 4.5,
      stock: 10
    },
    {
      id: '14',
      name: 'Sunset dense',
      description: "Гори на заході сонця.",
      category: 'VANILLA',
      price: 15.99,
      imageUrl: './products/vanilla/Sunset dense.webp',
      rating: 4.6,
      stock: 10
    },
    {
      id: '15',
      name: 'Seaside',
      description: "Гори і озеро, з маленьким фото гори та рослини на підвіконні.",
      category: 'VANILLA',
      price: 15.99,
      imageUrl: './products/vanilla/Seaside.webp',
      rating: 4.7,
      stock: 10
    },
    {
      id: '16',
      name: 'Creebet',
      description: "Картина Seaside, але яскрава рослина була замінена на голову моба Крипера.",
      category: 'VANILLA',
      price: 15.99,
      imageUrl: './products/vanilla/Creebet.webp',
      rating: 4.5,
      stock: 10
    },
    {
      id: '17',
      name: 'Match',
      description: "Рука, що тримає сірник і підпалює піксельний вогонь.",
      category: 'VANILLA',
      price: 15.99,
      imageUrl: './products/vanilla/Match.webp',
      rating: 4.6,
      stock: 10
    },
    {
      id: '18',
      name: 'Bust',
      description: "Маркус Аврелій серед піксельного вогню.",
      category: 'VANILLA',
      price: 15.99,
      imageUrl: './products/vanilla/Bust.webp',
      rating: 4.8,
      stock: 10
    },
    {
      id: '19',
      name: 'The Stage Is Set',
      description: "Сцена з гри Space Quest I, з персонажем Гремом з серії King's Quest, що з'являється двічі.",
      category: 'VANILLA',
      price: 15.99,
      imageUrl: './products/vanilla/The Stage Is Set.webp',
      rating: 4.7,
      stock: 10
    },
    {
      id: '20',
      name: 'The void',
      description: "Ангел, що молиться у порожнечу, з вогнем внизу.",
      category: 'VANILLA',
      price: 15.99,
      imageUrl: './products/vanilla/The void.webp',
      rating: 4.9,
      stock: 10
    },
    {
      id: '21',
      name: 'Skull and Roses',
      description: "Скелет вночі з червоними квітами на передньому плані. Картина була модифікована від оригіналу.",
      category: 'VANILLA',
      price: 15.99,
      imageUrl: './products/vanilla/Skull and Roses.webp',
      rating: 4.7,
      stock: 10
    },
    {
      id: '22',
      name: 'Wither',
      description: "Моб боса Wither.",
      category: 'VANILLA',
      price: 15.99,
      imageUrl: './products/vanilla/Wither.webp',
      rating: 5.0,
      stock: 10
    },
    {
      id: '23',
      name: 'Baroque',
      description: "Декорований горщик, торт і соняшник на темному фоні.",
      category: 'VANILLA',
      price: 15.99,
      imageUrl: './products/vanilla/Baroque.webp',
      rating: 4.5,
      stock: 10
    },
    {
      id: '24',
      name: 'Humble',
      description: "Двоє мешканців Minecraft перед будинком в селі, картина за мотивами «Американської готики» Гранта Вуда.",
      category: 'VANILLA',
      price: 15.99,
      imageUrl: './products/vanilla/Humble.webp',
      rating: 4.6,
      stock: 10
    }
  ,

  {
    id: '3вфівфі',
    name: 'Albanian',
    description: "A man wearing a fez next to a house and a bush.",
    category: 'VANILLA',
    price: 15.99,
    imageUrl: './products/vanilla/Albanian.webp',
    rating: 4.5,
    stock: 10,
  },
  {
    id: 'віфвф4',
    name: 'De_aztec 2',
    description: "De_aztec map from the game Counter Strike.",
    category: 'VANILLA',
    price: 15.99,
    imageUrl: './products/vanilla/De_aztec_2.webp',
    rating: 4.5,
    stock: 10,
  },
  {
    id: '5вфівф',
    name: 'Target Successfully Bombed',
    description: "De_dust2 map from the game Counter Strike, named “target successfully bombed” in reference to the game.",
    category: 'VANILLA',
    price: 15.99,
    imageUrl: './products/vanilla/Target_Successfully_Bombed.webp',
    rating: 4.5,
    stock: 10,
  },
  {
    id: '6вфівфі',
    name: 'Paradisträd',
    description: "Still life of two plants in pots.",
    category: 'VANILLA',
    price: 15.99,
    imageUrl: './products/vanilla/Paradisträd.webp',
    rating: 4.5,
    stock: 10,
  },
  {
    id: '7вфівфів',
    name: 'Wasteland',
    description: "Wasteland in the background and a rabbit is sitting on the windowsill.",
    category: 'VANILLA',
    price: 15.99,
    imageUrl: './products/vanilla/Wasteland.webp',
    rating: 4.5,
    stock: 10,
  },
  {
    id: 'вфів8',
    name: 'Meditative',
    description: "Minecraft’s removed rose, made after Salvador Dali’s Meditative Rose.",
    category: 'VANILLA',
    price: 15.99,
    imageUrl: './products/vanilla/Meditative.webp',
    rating: 4.5,
    stock: 10,
  },
  {
    id: 'вфів9',
    name: 'Wanderer',
    description: "Person standing, made after Caspar David Friedrich’s famous painting Wanderer above the Sea of Fog.",
    category: 'VANILLA',
    price: 15.99,
    imageUrl: './products/vanilla/Wanderer.webp',
    rating: 4.5,
    stock: 10,
  },
  {
    id: '1вфів0',
    name: 'Graham',
    description: "King Graham is the player character in the video game series King’s Quest.",
    category: 'VANILLA',
    price: 15.99,
    imageUrl: './products/vanilla/Graham.webp',
    rating: 4.5,
    stock: 10,
  },
  {
    id: '11фів',
    name: 'Prairie Ride',
    description: "Minecraft default skin Noor riding a horse, made after Frederic Remington’s The Cowboy.",
    category: 'VANILLA',
    price: 15.99,
    imageUrl: './products/vanilla/Prairie_Ride.webp',
    rating: 4.5,
    stock: 10,
  },
  {
    id: '12йц',
    name: 'The Pool',
    description: "People resting and taking a bath in a square pool.",
    category: 'VANILLA',
    price: 15.99,
    imageUrl: './products/vanilla/The_Pool.webp',
    rating: 4.5,
    stock: 10,
  },




  {
    id: '26',
    name: 'Skeleton',
    description: 'Картина зі скелетом, що бореться з павуком.',
    category: 'MINECRAFT_ART',
    price: 12.99,
    imageUrl:
    './products/arts/1.jpg',
    rating: 4.6,
    stock: 15,
  },
  {
    id: '27',
    name: 'Kebab',
    description: "Картина, на якій зображені шматочки м'яса на паличці.",
    category: 'MINECRAFT_ART',
    price: 10.99,
    imageUrl:
    './products/arts/2.jpg',
    rating: 4.5,
    stock: 12,
  },
  {
    id: '28',
    name: 'Aztec',
    description: 'Абстрактний візерунок у стилі ацтеків.',
    category: 'MINECRAFT_ART',
    price: 14.99,
    imageUrl:
    './products/arts/3.jpg',
    rating: 4.7,
    stock: 7,
  },
  {
    id: '29',
    name: 'Pointer',
    description: 'Картина з лицарем, що вказує на щось.',
    category: 'MINECRAFT_ART',
    price: 16.99,
    imageUrl:
    './products/arts/4.jpg',
    rating: 4.9,
    stock: 5,
  },
  {
    id: '25',
    name: 'Burning Skull',
    description: 'Картина із зображенням палаючого черепа.',
    category: 'MINECRAFT_ART',
    price: 17.99,
    imageUrl:
      './products/arts/5.jpg',
    rating: 4.7,
    stock: 8,
  },
];
